# Generated by Django 5.0.7 on 2024-07-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_01', '0002_contact_age_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
