# Generated by Django 5.0.7 on 2024-07-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_01', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.CharField(default=4, max_length=1000000000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
