# Generated by Django 5.0.7 on 2024-07-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_01', '0005_blog_user_alter_contact_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default=4, upload_to='img/'),
            preserve_default=False,
        ),
    ]
