# Generated by Django 5.0.7 on 2024-07-29 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_01', '0006_blog_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='img',
        ),
    ]
